{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0d4b55a0",
   "metadata": {},
   "source": [
    "실습 3: 데이터 로드 및 기본 탐색\n",
    "================================\n",
    "CSIC 2010 HTTP 데이터셋(csic2010_requests.csv)을 로드하고\n",
    "HTTP 요청의 구조와 정상/공격 분포를 파악합니다.\n",
    "\n",
    "실행 방법: JupyterLab에서 이 노트북을 열고 셀을 위에서부터 Shift+Enter로 순차 실행\n",
    "사전 준비: python download_csic2010.py 로 csic2010_requests.csv 생성\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "23e423c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# %% [Setup] 패키지 import\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b655818b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=================================================================\n",
      "  [실습 3] CSIC 2010 HTTP 데이터 로드 및 기본 탐색\n",
      "=================================================================\n",
      "\n",
      "  데이터 로드 완료!\n",
      "  파일: C:\\Users\\white\\Desktop\\강의\\동양\\빅데이터분석프로젝트\\BigDataAnalysis\\7_week\\csic2010_requests.csv\n",
      "  크기: 10,000행 x 18열\n"
     ]
    }
   ],
   "source": [
    "# %% [1] 데이터 로드\n",
    "# ============================================================\n",
    "# 1. 데이터 로드\n",
    "# ============================================================\n",
    "print(\"=\" * 65)\n",
    "print(\"  [실습 3] CSIC 2010 HTTP 데이터 로드 및 기본 탐색\")\n",
    "print(\"=\" * 65)\n",
    "\n",
    "# Jupyter 셀 모드에서도 동작하도록 __file__ 처리\n",
    "try:\n",
    "    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))\n",
    "except NameError:\n",
    "    SCRIPT_DIR = os.getcwd()\n",
    "\n",
    "data_path = os.path.join(SCRIPT_DIR, \"csic2010_requests.csv\")\n",
    "\n",
    "if not os.path.exists(data_path):\n",
    "    print(f\"\\n  !! csic2010_requests.csv 파일이 없습니다.\")\n",
    "    print(f\"  >> 먼저 download_csic2010.py를 실행하세요.\")\n",
    "    exit()\n",
    "\n",
    "df = pd.read_csv(data_path)\n",
    "\n",
    "print(f\"\\n  데이터 로드 완료!\")\n",
    "print(f\"  파일: {data_path}\")\n",
    "print(f\"  크기: {df.shape[0]:,}행 x {df.shape[1]}열\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fc355042-633c-44a0-9637-0e45cba1176e",
   "metadata": {},
   "source": [
    "### 데이터 탐색 메서드 정리\n",
    "\n",
    "| 메서드 | 역할 | 확인 포인트 |\n",
    "|--------|------|-------------|\n",
    "| `df.shape` | (행 수, 열 수) 튜플 반환 | 데이터 규모 파악 |\n",
    "| `df.head()` | 처음 5행 표시 | 데이터 형태 미리보기 |\n",
    "| `df.tail()` | 마지막 5행 표시 | 데이터 끝부분 확인 |\n",
    "| `df.head(10)` | 처음 10행 표시 | 숫자 지정 가능 |\n",
    "| `df.info()` | 컬럼별 데이터 타입, Non-Null 수 | 타입 이상, Null 존재 여부 |\n",
    "| `df.describe()` | 수치형 컬럼 기술통계 | 평균, 표준편차, 최솟값, 최댓값, 사분위수 |\n",
    "| `df.dtypes` | 각 컬럼의 데이터 타입 | object, int64, float64 등 확인 |\n",
    "| `df.columns` | 컬럼명 목록 (Index 객체) | 오타, 공백 포함 여부 확인 |\n",
    "| `df.nunique()` | 컬럼별 고유값 수 | 범주형 변수 판별 기준 |\n",
    "| `df[\"col\"].value_counts()` | 값별 빈도 (내림차순) | 범주 분포 확인 |"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "1eb116a5-294b-4a26-8db0-e31432d67c35",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10000, 18)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5ac09eba-a32e-4abd-9bcd-aeed2aa41857",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>classification</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>10000.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>0.410500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>0.491949</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       classification\n",
       "count    10000.000000\n",
       "mean         0.410500\n",
       "std          0.491949\n",
       "min          0.000000\n",
       "25%          0.000000\n",
       "50%          0.000000\n",
       "75%          1.000000\n",
       "max          1.000000"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3295c8df-1c3d-488a-8a87-2200dc11ec7f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 10000 entries, 0 to 9999\n",
      "Data columns (total 18 columns):\n",
      " #   Column           Non-Null Count  Dtype \n",
      "---  ------           --------------  ----- \n",
      " 0   label            10000 non-null  object\n",
      " 1   method           10000 non-null  object\n",
      " 2   url              9961 non-null   object\n",
      " 3   http_version     10000 non-null  object\n",
      " 4   host             10000 non-null  object\n",
      " 5   user_agent       10000 non-null  object\n",
      " 6   pragma           10000 non-null  object\n",
      " 7   cache_control    10000 non-null  object\n",
      " 8   accept           9929 non-null   object\n",
      " 9   accept_encoding  10000 non-null  object\n",
      " 10  accept_charset   10000 non-null  object\n",
      " 11  language         10000 non-null  object\n",
      " 12  cookie           10000 non-null  object\n",
      " 13  content_type     3016 non-null   object\n",
      " 14  content_length   3016 non-null   object\n",
      " 15  connection       10000 non-null  object\n",
      " 16  body             3016 non-null   object\n",
      " 17  classification   10000 non-null  int64 \n",
      "dtypes: int64(1), object(17)\n",
      "memory usage: 1.4+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "bbaed0ab-f5fd-49bd-96a6-d2d05323f1c8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>label</th>\n",
       "      <th>method</th>\n",
       "      <th>url</th>\n",
       "      <th>http_version</th>\n",
       "      <th>host</th>\n",
       "      <th>user_agent</th>\n",
       "      <th>pragma</th>\n",
       "      <th>cache_control</th>\n",
       "      <th>accept</th>\n",
       "      <th>accept_encoding</th>\n",
       "      <th>accept_charset</th>\n",
       "      <th>language</th>\n",
       "      <th>cookie</th>\n",
       "      <th>content_type</th>\n",
       "      <th>content_length</th>\n",
       "      <th>connection</th>\n",
       "      <th>body</th>\n",
       "      <th>classification</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>9995</th>\n",
       "      <td>Normal</td>\n",
       "      <td>GET</td>\n",
       "      <td>/tienda1/global/estilos.css</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=E920E69471A011579F0720FCD90BFF2E</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>close</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9996</th>\n",
       "      <td>Normal</td>\n",
       "      <td>GET</td>\n",
       "      <td>/tienda1/imagenes/cmenbul.gif</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=36E12256C60662E0852525C2A204DEED</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>close</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9997</th>\n",
       "      <td>Normal</td>\n",
       "      <td>GET</td>\n",
       "      <td>/tienda1/global/titulo.jsp</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=25D7022C3B580D1D6689811BF346DCB5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>close</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9998</th>\n",
       "      <td>Normal</td>\n",
       "      <td>POST</td>\n",
       "      <td>/tienda1/publico/anadir.jsp</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=2436A5157F43E5E3DECE11F1C390CFF8</td>\n",
       "      <td>application/x-www-form-urlencoded</td>\n",
       "      <td>Content-Length: 71</td>\n",
       "      <td>Connection: close</td>\n",
       "      <td>id=3&amp;nombre=Queso+Manchego&amp;precio=85&amp;cantidad=...</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9999</th>\n",
       "      <td>Anomalous</td>\n",
       "      <td>POST</td>\n",
       "      <td>/tienda1/publico/caracteristicas.jsp</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=AAECDF742DAEAD8C3F901AF615560423</td>\n",
       "      <td>application/x-www-form-urlencoded</td>\n",
       "      <td>Content-Length: 5</td>\n",
       "      <td>Connection: close</td>\n",
       "      <td>idA=2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          label method                                   url http_version  \\\n",
       "9995     Normal    GET           /tienda1/global/estilos.css     HTTP/1.1   \n",
       "9996     Normal    GET         /tienda1/imagenes/cmenbul.gif     HTTP/1.1   \n",
       "9997     Normal    GET            /tienda1/global/titulo.jsp     HTTP/1.1   \n",
       "9998     Normal   POST           /tienda1/publico/anadir.jsp     HTTP/1.1   \n",
       "9999  Anomalous   POST  /tienda1/publico/caracteristicas.jsp     HTTP/1.1   \n",
       "\n",
       "                host                                         user_agent  \\\n",
       "9995  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9996  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9997  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9998  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9999  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "\n",
       "        pragma cache_control  \\\n",
       "9995  no-cache      no-cache   \n",
       "9996  no-cache      no-cache   \n",
       "9997  no-cache      no-cache   \n",
       "9998  no-cache      no-cache   \n",
       "9999  no-cache      no-cache   \n",
       "\n",
       "                                                 accept  \\\n",
       "9995  text/xml,application/xml,application/xhtml+xml...   \n",
       "9996  text/xml,application/xml,application/xhtml+xml...   \n",
       "9997  text/xml,application/xml,application/xhtml+xml...   \n",
       "9998  text/xml,application/xml,application/xhtml+xml...   \n",
       "9999  text/xml,application/xml,application/xhtml+xml...   \n",
       "\n",
       "                       accept_encoding               accept_charset language  \\\n",
       "9995  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9996  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9997  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9998  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9999  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "\n",
       "                                           cookie  \\\n",
       "9995  JSESSIONID=E920E69471A011579F0720FCD90BFF2E   \n",
       "9996  JSESSIONID=36E12256C60662E0852525C2A204DEED   \n",
       "9997  JSESSIONID=25D7022C3B580D1D6689811BF346DCB5   \n",
       "9998  JSESSIONID=2436A5157F43E5E3DECE11F1C390CFF8   \n",
       "9999  JSESSIONID=AAECDF742DAEAD8C3F901AF615560423   \n",
       "\n",
       "                           content_type      content_length  \\\n",
       "9995                                NaN                 NaN   \n",
       "9996                                NaN                 NaN   \n",
       "9997                                NaN                 NaN   \n",
       "9998  application/x-www-form-urlencoded  Content-Length: 71   \n",
       "9999  application/x-www-form-urlencoded   Content-Length: 5   \n",
       "\n",
       "             connection                                               body  \\\n",
       "9995              close                                                NaN   \n",
       "9996              close                                                NaN   \n",
       "9997              close                                                NaN   \n",
       "9998  Connection: close  id=3&nombre=Queso+Manchego&precio=85&cantidad=...   \n",
       "9999  Connection: close                                              idA=2   \n",
       "\n",
       "      classification  \n",
       "9995               0  \n",
       "9996               0  \n",
       "9997               0  \n",
       "9998               0  \n",
       "9999               1  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "3fb2871b-f631-4731-8f89-fe1331441fe7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "label                  2\n",
       "method                 3\n",
       "url                 2692\n",
       "http_version           1\n",
       "host                   2\n",
       "user_agent             1\n",
       "pragma                 1\n",
       "cache_control          1\n",
       "accept                 1\n",
       "accept_encoding        1\n",
       "accept_charset         1\n",
       "language               1\n",
       "cookie             10000\n",
       "content_type           1\n",
       "content_length       273\n",
       "connection             2\n",
       "body                2184\n",
       "classification         2\n",
       "dtype: int64"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.nunique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "71812ebc-cf79-4ff4-b7f8-a8c579d0550b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "method\n",
       "GET    6984\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 해당 행의 method 컬럼만 추출\n",
    "df.loc[df[\"content_length\"].isna(), \"method\"].value_counts()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e375b737",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [2] 데이터 기본 정보\n",
      "─────────────────────────────────────────────────────────────────\n",
      "\n",
      "  전체 HTTP 요청 수: 10,000건\n",
      "  컬럼 수: 18개\n",
      "  메모리 사용량: 11.9 MB\n"
     ]
    }
   ],
   "source": [
    "# %% [2] 기본 정보 확인\n",
    "# ============================================================\n",
    "# 2. 기본 정보 확인\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [2] 데이터 기본 정보\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "print(f\"\\n  전체 HTTP 요청 수: {len(df):,}건\")\n",
    "print(f\"  컬럼 수: {df.shape[1]}개\")\n",
    "print(f\"  메모리 사용량: {df.memory_usage(deep=True).sum() / 1024 / 1024:.1f} MB\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "67f29552",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [4] 라벨 분포 (Normal vs Anomalous) ★\n",
      "─────────────────────────────────────────────────────────────────\n",
      "\n",
      "  라벨              |       건수 |     비율 | 시각화\n",
      "  ───────────────-+-────────-+-──────-+-──────────────────────────────\n",
      "  Normal          |    5,895 |  59.0% | █████████████████████████████\n",
      "  Anomalous       |    4,105 |  41.0% | ████████████████████\n",
      "\n",
      "  >> 정상(5,895건) vs 공격(4,105건)\n"
     ]
    }
   ],
   "source": [
    "# %% [4] 라벨 분포 ★★★ (Normal vs Anomalous)\n",
    "# ============================================================\n",
    "# 4. 라벨(Label) 분포 확인 ★★★\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [4] 라벨 분포 (Normal vs Anomalous) ★\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "label_counts = df[\"label\"].value_counts()\n",
    "label_ratio = df[\"label\"].value_counts(normalize=True) * 100\n",
    "\n",
    "print(f\"\\n  {'라벨':<15s} | {'건수':>8s} | {'비율':>6s} | 시각화\")\n",
    "print(f\"  {'─' * 15}-+-{'─' * 8}-+-{'─' * 6}-+-{'─' * 30}\")\n",
    "\n",
    "for label in label_counts.index:\n",
    "    count = label_counts[label]\n",
    "    ratio = label_ratio[label]\n",
    "    bar = \"█\" * int(ratio / 2)\n",
    "    print(f\"  {label:<15s} | {count:>8,} | {ratio:>5.1f}% | {bar}\")\n",
    "\n",
    "print(f\"\\n  >> 정상({label_counts.get('Normal', 0):,}건) vs \"\n",
    "      f\"공격({label_counts.get('Anomalous', 0):,}건)\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "9579bc51-a45c-4c44-b753-702ff16c2fb2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "label\n",
       "Normal       5895\n",
       "Anomalous    4105\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[\"label\"].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "5ffba63b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [5] HTTP 메서드 분포\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  GET   :    6,984건 ( 69.8%) ██████████████████████████████████\n",
      "  POST  :    2,945건 ( 29.4%) ██████████████\n",
      "  PUT   :       71건 (  0.7%) \n"
     ]
    }
   ],
   "source": [
    "# %% [5] HTTP 메서드 분포\n",
    "# ============================================================\n",
    "# 5. HTTP 메서드 분포\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [5] HTTP 메서드 분포\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "method_counts = df[\"method\"].value_counts()\n",
    "for method, count in method_counts.items():\n",
    "    pct = count / len(df) * 100\n",
    "    bar = \"█\" * int(pct / 2)\n",
    "    print(f\"  {method:6s}: {count:>8,}건 ({pct:5.1f}%) {bar}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "cbc93ca7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [6] 메서드별 정상/공격 분포\n",
      "─────────────────────────────────────────────────────────────────\n",
      "\n",
      "label   Anomalous  Normal\n",
      "method                   \n",
      "GET          2434    4550\n",
      "POST         1600    1345\n",
      "PUT            71       0\n",
      "\n",
      "  GET: 공격 비율 34.9% ← 공격 비율 높음!\n",
      "  POST: 공격 비율 54.3% ← 공격 비율 높음!\n",
      "  PUT: 공격 비율 100.0% ← 공격 비율 높음!\n"
     ]
    }
   ],
   "source": [
    "# %% [6] 메서드 × 라벨 교차 분석\n",
    "# ============================================================\n",
    "# 6. 메서드별 정상/공격 교차 분석\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [6] 메서드별 정상/공격 분포\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "cross = pd.crosstab(df[\"method\"], df[\"label\"])\n",
    "print(f\"\\n{cross.to_string()}\")\n",
    "\n",
    "# 공격 비율이 높은 메서드 확인\n",
    "for method in cross.index:\n",
    "    total = cross.loc[method].sum()\n",
    "    anomalous = cross.loc[method].get(\"Anomalous\", 0)\n",
    "    ratio = anomalous / total * 100 if total > 0 else 0\n",
    "    print(f\"\\n  {method}: 공격 비율 {ratio:.1f}%\", end=\"\")\n",
    "    if ratio > 30:\n",
    "        print(\" ← 공격 비율 높음!\", end=\"\")\n",
    "print()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "9beece51",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [7] 실제 HTTP 요청 샘플 확인 ★\n",
      "─────────────────────────────────────────────────────────────────\n",
      "\n",
      "  ═══ 정상 요청 (Normal) ═══\n",
      "  메서드: GET\n",
      "  URL:    /tienda1/miembros/imagenes/ogono.jpg\n",
      "  쿠키:   JSESSIONID=FDC7D99F5F76056DB0AF6D58232FA236\n",
      "  본문:   (없음)\n",
      "\n",
      "  ═══ 공격 요청 (Anomalous) — 3건 ═══\n",
      "\n",
      "  --- 공격 #1 ---\n",
      "  메서드: GET\n",
      "  URL:    /WebSphereSamples/SingleSamples/Increment/increment.html\n",
      "  본문:   (없음)\n",
      "  → 1교시에서 배운 공격 패턴을 찾아보세요!\n",
      "\n",
      "  --- 공격 #2 ---\n",
      "  메서드: GET\n",
      "  URL:    /tienda1/publico/carrito.jsp/asf-logo-wide\n",
      "  본문:   (없음)\n",
      "  → 1교시에서 배운 공격 패턴을 찾아보세요!\n",
      "\n",
      "  --- 공격 #3 ---\n",
      "  메서드: GET\n",
      "  URL:    /tienda1/global/estilos.css/asf-logo-wide.gif/.Old\n",
      "  본문:   (없음)\n",
      "  → 1교시에서 배운 공격 패턴을 찾아보세요!\n"
     ]
    }
   ],
   "source": [
    "# %% [7] 실제 HTTP 요청 샘플 ★★★\n",
    "# ============================================================\n",
    "# 7. 실제 HTTP 요청 확인 ★★★\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [7] 실제 HTTP 요청 샘플 확인 ★\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "# 정상 요청 1건\n",
    "print(f\"\\n  ═══ 정상 요청 (Normal) ═══\")\n",
    "normal = df[df[\"label\"] == \"Normal\"].iloc[0]\n",
    "print(f\"  메서드: {normal['method']}\")\n",
    "print(f\"  URL:    {normal['url'][:100]}{'...' if len(str(normal['url'])) > 100 else ''}\")\n",
    "print(f\"  쿠키:   {str(normal['cookie'])[:60]}{'...' if len(str(normal['cookie'])) > 60 else ''}\")\n",
    "body = str(normal[\"body\"]) if pd.notna(normal[\"body\"]) and normal[\"body\"] else \"(없음)\"\n",
    "print(f\"  본문:   {body[:100]}\")\n",
    "\n",
    "# 공격 요청 3건\n",
    "print(f\"\\n  ═══ 공격 요청 (Anomalous) — 3건 ═══\")\n",
    "anomalous = df[df[\"label\"] == \"Anomalous\"].sample(3, random_state=42)\n",
    "for i, (_, row) in enumerate(anomalous.iterrows(), 1):\n",
    "    print(f\"\\n  --- 공격 #{i} ---\")\n",
    "    print(f\"  메서드: {row['method']}\")\n",
    "    url_display = str(row[\"url\"])[:120]\n",
    "    print(f\"  URL:    {url_display}{'...' if len(str(row['url'])) > 120 else ''}\")\n",
    "    body = str(row[\"body\"]) if pd.notna(row[\"body\"]) and row[\"body\"] else \"(없음)\"\n",
    "    print(f\"  본문:   {body[:120]}{'...' if len(body) > 120 else ''}\")\n",
    "    print(f\"  → 1교시에서 배운 공격 패턴을 찾아보세요!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "971febe8-8d16-4754-a875-a5b04746e4dc",
   "metadata": {},
   "source": [
    "CSIC 2010 데이터셋의 전형적인 경로 기반 정찰(Path-based Reconnaissance) 공격입니다.\n",
    "\n",
    "각 공격 분석\n",
    "공격 #1 — 기본 샘플 파일 탐색 (Default File Probing)\n",
    "\n",
    "/WebSphereSamples/SingleSamples/Increment/increment.html\n",
    "IBM WebSphere 설치 시 기본 제공되는 샘플 애플리케이션 경로\n",
    "관리자가 운영 서버에서 삭제하지 않은 기본 샘플을 노려 알려진 취약점 악용\n",
    "정상 사용자는 절대 접근하지 않는 경로\n",
    "공격 #2 — 경로 파라미터 변조 (Path Manipulation)\n",
    "\n",
    "/tienda1/publico/carrito.jsp/asf-logo-wide\n",
    "                          ↑\n",
    "                   JSP 뒤에 가짜 경로 추가\n",
    ".jsp 확장자 뒤에 부가 경로(/asf-logo-wide)를 붙여 서버의 경로 파싱 로직 혼란 유도\n",
    "일부 서버에서 인증/필터 우회 가능 (Path Confusion / Filter Bypass)\n",
    "공격 #3 — 백업 파일 접근 시도 (Backup File Access)\n",
    "\n",
    "/tienda1/global/estilos.css/asf-logo-wide.gif/.Old\n",
    "                                              ↑\n",
    "                                       백업 파일 확장자\n",
    "끝의 .Old는 백업/이전 버전 파일을 노리는 전형적 패턴 (.bak, .old, .backup, ~ 등과 동일 부류)\n",
    "소스 코드 노출, 구버전 취약점 악용 목적"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "d180247b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [8] URL 길이 기본 통계\n",
      "─────────────────────────────────────────────────────────────────\n",
      "\n",
      "  구분           |       평균 |      중앙값 |       최대\n",
      "  ────────────-+-────────-+-────────-+-────────\n",
      "  Normal       |       51 |       29 |    332.0\n",
      "  Anomalous    |       77 |       33 |    865.0\n",
      "\n",
      "  >> 공격 요청의 URL이 평균적으로 더 깁니다! (공격 코드가 삽입되므로)\n"
     ]
    }
   ],
   "source": [
    "# %% [8] URL 길이 기본 통계\n",
    "# ============================================================\n",
    "# 8. URL 길이 기본 통계\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [8] URL 길이 기본 통계\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "df[\"url_length\"] = df[\"url\"].str.len()\n",
    "\n",
    "print(f\"\\n  {'구분':<12s} | {'평균':>8s} | {'중앙값':>8s} | {'최대':>8s}\")\n",
    "print(f\"  {'─' * 12}-+-{'─' * 8}-+-{'─' * 8}-+-{'─' * 8}\")\n",
    "\n",
    "for label in [\"Normal\", \"Anomalous\"]:\n",
    "    subset = df[df[\"label\"] == label][\"url_length\"]\n",
    "    print(f\"  {label:<12s} | {subset.mean():>8.0f} | {subset.median():>8.0f} | {subset.max():>8,}\")\n",
    "\n",
    "print(f\"\\n  >> 공격 요청의 URL이 평균적으로 더 깁니다! (공격 코드가 삽입되므로)\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "a48c9f88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "─────────────────────────────────────────────────────────────────\n",
      "  [9] 데이터 품질 확인\n",
      "─────────────────────────────────────────────────────────────────\n",
      "\n",
      "  결측치가 있는 컬럼:\n",
      "    - url: 39건\n",
      "    - accept: 71건\n",
      "    - content_type: 6,984건\n",
      "    - content_length: 6,984건\n",
      "    - body: 6,984건\n",
      "    - url_length: 39건\n",
      "\n",
      "  본문(body)이 비어있는 요청: 6,984건 (대부분 GET 요청)\n",
      "\n",
      "=================================================================\n",
      "  실습 3 완료! 다음: streamlit run eda_visualization.py\n",
      "=================================================================\n"
     ]
    }
   ],
   "source": [
    "# %% [9] 데이터 품질 확인\n",
    "# ============================================================\n",
    "# 9. 데이터 품질 확인\n",
    "# ============================================================\n",
    "print(f\"\\n{'─' * 65}\")\n",
    "print(\"  [9] 데이터 품질 확인\")\n",
    "print(f\"{'─' * 65}\")\n",
    "\n",
    "# 결측치 확인\n",
    "missing = df.isnull().sum()\n",
    "missing_cols = missing[missing > 0]\n",
    "print(f\"\\n  결측치가 있는 컬럼:\")\n",
    "if len(missing_cols) > 0:\n",
    "    for col, cnt in missing_cols.items():\n",
    "        print(f\"    - {col}: {cnt:,}건\")\n",
    "else:\n",
    "    print(\"    없음 (body, cookie 등은 빈 문자열)\")\n",
    "\n",
    "# 빈 body (GET 요청)\n",
    "empty_body = df[\"body\"].fillna(\"\").eq(\"\").sum()\n",
    "print(f\"\\n  본문(body)이 비어있는 요청: {empty_body:,}건 (대부분 GET 요청)\")\n",
    "\n",
    "print(f\"\\n{'=' * 65}\")\n",
    "print(\"  실습 3 완료! 다음: streamlit run eda_visualization.py\")\n",
    "print(f\"{'=' * 65}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "cbe07f67-da04-46a0-9e00-26839171fb47",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>label</th>\n",
       "      <th>method</th>\n",
       "      <th>url</th>\n",
       "      <th>http_version</th>\n",
       "      <th>host</th>\n",
       "      <th>user_agent</th>\n",
       "      <th>pragma</th>\n",
       "      <th>cache_control</th>\n",
       "      <th>accept</th>\n",
       "      <th>accept_encoding</th>\n",
       "      <th>accept_charset</th>\n",
       "      <th>language</th>\n",
       "      <th>cookie</th>\n",
       "      <th>content_type</th>\n",
       "      <th>content_length</th>\n",
       "      <th>connection</th>\n",
       "      <th>body</th>\n",
       "      <th>classification</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>9995</th>\n",
       "      <td>Normal</td>\n",
       "      <td>GET</td>\n",
       "      <td>/tienda1/global/estilos.css</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=E920E69471A011579F0720FCD90BFF2E</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>close</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9996</th>\n",
       "      <td>Normal</td>\n",
       "      <td>GET</td>\n",
       "      <td>/tienda1/imagenes/cmenbul.gif</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=36E12256C60662E0852525C2A204DEED</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>close</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9997</th>\n",
       "      <td>Normal</td>\n",
       "      <td>GET</td>\n",
       "      <td>/tienda1/global/titulo.jsp</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=25D7022C3B580D1D6689811BF346DCB5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>close</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9998</th>\n",
       "      <td>Normal</td>\n",
       "      <td>POST</td>\n",
       "      <td>/tienda1/publico/anadir.jsp</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=2436A5157F43E5E3DECE11F1C390CFF8</td>\n",
       "      <td>application/x-www-form-urlencoded</td>\n",
       "      <td>Content-Length: 71</td>\n",
       "      <td>Connection: close</td>\n",
       "      <td>id=3&amp;nombre=Queso+Manchego&amp;precio=85&amp;cantidad=...</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9999</th>\n",
       "      <td>Anomalous</td>\n",
       "      <td>POST</td>\n",
       "      <td>/tienda1/publico/caracteristicas.jsp</td>\n",
       "      <td>HTTP/1.1</td>\n",
       "      <td>localhost:8080</td>\n",
       "      <td>Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>no-cache</td>\n",
       "      <td>text/xml,application/xml,application/xhtml+xml...</td>\n",
       "      <td>x-gzip, x-deflate, gzip, deflate</td>\n",
       "      <td>utf-8, utf-8;q=0.5, *;q=0.5</td>\n",
       "      <td>en</td>\n",
       "      <td>JSESSIONID=AAECDF742DAEAD8C3F901AF615560423</td>\n",
       "      <td>application/x-www-form-urlencoded</td>\n",
       "      <td>Content-Length: 5</td>\n",
       "      <td>Connection: close</td>\n",
       "      <td>idA=2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          label method                                   url http_version  \\\n",
       "9995     Normal    GET           /tienda1/global/estilos.css     HTTP/1.1   \n",
       "9996     Normal    GET         /tienda1/imagenes/cmenbul.gif     HTTP/1.1   \n",
       "9997     Normal    GET            /tienda1/global/titulo.jsp     HTTP/1.1   \n",
       "9998     Normal   POST           /tienda1/publico/anadir.jsp     HTTP/1.1   \n",
       "9999  Anomalous   POST  /tienda1/publico/caracteristicas.jsp     HTTP/1.1   \n",
       "\n",
       "                host                                         user_agent  \\\n",
       "9995  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9996  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9997  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9998  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "9999  localhost:8080  Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...   \n",
       "\n",
       "        pragma cache_control  \\\n",
       "9995  no-cache      no-cache   \n",
       "9996  no-cache      no-cache   \n",
       "9997  no-cache      no-cache   \n",
       "9998  no-cache      no-cache   \n",
       "9999  no-cache      no-cache   \n",
       "\n",
       "                                                 accept  \\\n",
       "9995  text/xml,application/xml,application/xhtml+xml...   \n",
       "9996  text/xml,application/xml,application/xhtml+xml...   \n",
       "9997  text/xml,application/xml,application/xhtml+xml...   \n",
       "9998  text/xml,application/xml,application/xhtml+xml...   \n",
       "9999  text/xml,application/xml,application/xhtml+xml...   \n",
       "\n",
       "                       accept_encoding               accept_charset language  \\\n",
       "9995  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9996  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9997  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9998  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "9999  x-gzip, x-deflate, gzip, deflate  utf-8, utf-8;q=0.5, *;q=0.5       en   \n",
       "\n",
       "                                           cookie  \\\n",
       "9995  JSESSIONID=E920E69471A011579F0720FCD90BFF2E   \n",
       "9996  JSESSIONID=36E12256C60662E0852525C2A204DEED   \n",
       "9997  JSESSIONID=25D7022C3B580D1D6689811BF346DCB5   \n",
       "9998  JSESSIONID=2436A5157F43E5E3DECE11F1C390CFF8   \n",
       "9999  JSESSIONID=AAECDF742DAEAD8C3F901AF615560423   \n",
       "\n",
       "                           content_type      content_length  \\\n",
       "9995                                NaN                 NaN   \n",
       "9996                                NaN                 NaN   \n",
       "9997                                NaN                 NaN   \n",
       "9998  application/x-www-form-urlencoded  Content-Length: 71   \n",
       "9999  application/x-www-form-urlencoded   Content-Length: 5   \n",
       "\n",
       "             connection                                               body  \\\n",
       "9995              close                                                NaN   \n",
       "9996              close                                                NaN   \n",
       "9997              close                                                NaN   \n",
       "9998  Connection: close  id=3&nombre=Queso+Manchego&precio=85&cantidad=...   \n",
       "9999  Connection: close                                              idA=2   \n",
       "\n",
       "      classification  \n",
       "9995               0  \n",
       "9996               0  \n",
       "9997               0  \n",
       "9998               0  \n",
       "9999               1  "
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "a2e68778-297d-4062-942e-8a3a57cd7c51",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>classification</th>\n",
       "      <th>url_length</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>10000.000000</td>\n",
       "      <td>9961.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>0.410500</td>\n",
       "      <td>61.536994</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>0.491949</td>\n",
       "      <td>78.103567</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>0.000000</td>\n",
       "      <td>27.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>0.000000</td>\n",
       "      <td>29.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>1.000000</td>\n",
       "      <td>48.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>1.000000</td>\n",
       "      <td>865.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       classification   url_length\n",
       "count    10000.000000  9961.000000\n",
       "mean         0.410500    61.536994\n",
       "std          0.491949    78.103567\n",
       "min          0.000000     1.000000\n",
       "25%          0.000000    27.000000\n",
       "50%          0.000000    29.000000\n",
       "75%          1.000000    48.000000\n",
       "max          1.000000   865.000000"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fee2a5c6-84e3-4946-9336-4e4dff44e203",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
